# Generated by Django 4.1.3 on 2023-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50, verbose_name='Jméno')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='participants',
            field=models.ManyToManyField(to='chronicle.participant'),
        ),
    ]
