# Generated by Django 4.1.3 on 2023-01-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_tag_record_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name_plural': 'Účastníci'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name_plural': 'Záznamy'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tagy'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Typy'},
        ),
        migrations.AlterField(
            model_name='record',
            name='participants',
            field=models.ManyToManyField(to='chronicle.participant', verbose_name='Účastníci'),
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(to='chronicle.tag', verbose_name='Tagy'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chronicle.type', verbose_name='Typ'),
        ),
    ]
